### ISSUE TITLE
I can't lanch the psvimgtools-fronted

### ISSUE THREAD

**Issue by kostaszaxos050** [SilicaAndPina/psvimgtools-frontend#67] opened 2018-01-28 20:39 UTC
Here is a screenshot before it completely closes can you help me? https://www.dropbox.com/s/y7jlef8xo51y5ra/Screenshot_244.png?dl=0

**Comment by SilicaAndPina** [comment] 2018-02-02 08:29
.encode("UTF-8") on filepaths?

**Comment by kostaszaxos050** [comment] 2018-02-03 06:35
If I understand right and this is a file that I must have. I don't have it

**Comment by chronoss09** [comment] 2018-02-04 03:21
The latest version does not start :(

**Comment by SilicaAndPina** [comment] 2018-02-04 23:02
issue is you have non-unicode characters in your windows username or somewhere in the path where psvimgtools is stored. ill fix it in the next build ..

**Comment by SilicaAndPina** [comment] 2018-02-04 23:04
it definately works on windows i acturally programmed it on windows this time because my linux pc was broken ...

**Comment by SilicaAndPina** [comment] 2018-02-04 23:08
this is a duplicate of #64 please put all further discussion there.

**Closed by SilicaAndPina** 2018-02-04 23:08 UTC
