### ISSUE TITLE
ClonePSP Issues

### ISSUE THREAD

**Issue by Lykie** [SilicaAndPina/psvimgtools-frontend#82] opened 2018-04-30 15:39 UTC
Upon reaching the Clone Bubble menu, pressing "Random TitleID" gives me:

`Generating Random TitleID
TitleID: PSVIM9226
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1540, in __call__
  File "easyinstallers/ClonePSP/clone.py", line 93, in <lambda>
    self.Button2.configure(command=lambda: clone_support.random(oldtitleid,account))
  File "easyinstallers/ClonePSP/clone_support.py", line 27, in random
    set(newTitleId2,oldTitleId2,account)
  File "easyinstallers/ClonePSP/clone_support.py", line 40, in set
    filedata = filedata.replace(oldTitleId, newTitleId)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 8: ordinal not in range(128)`

Manually setting my TitleID (I chose "PSPCLONE1") gives me:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1540, in __call__
  File "easyinstallers/ClonePSP/clone.py", line 87, in <lambda>
    self.Button1.configure(command=lambda: clone_support.set(self.titleid.get(),oldtitleid,account))
  File "easyinstallers/ClonePSP/clone_support.py", line 40, in set
    filedata = filedata.replace(oldTitleId, newTitleId)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 8: ordinal not in range(128)`

On an unrelated note, the Puyo Puyo Tetris Demo on the CMBackups link in the readme is corrupted. It's only 24 MB whereas the demo's size is listed as almost 200 MB.

**Comment by SilicaAndPina** [comment] 2018-05-01 10:33
this shit is so fucing broken i cba fixing it anymore... 
why cant python just fucking read shit as bytes *grr*

**Comment by SilicaAndPina** [comment] 2018-05-22 11:14
lol ok
fine ill fix it. i think i have an idea

**Comment by SilicaAndPina** [comment] 2018-05-22 11:15
i just gotta make sure everything is being treated as bytes. . .

**Comment by SilicaAndPina** [comment] 2018-05-22 11:16
anyway this is a duplicate of #76 so im gonna close this please move all further discussion here

**Closed by SilicaAndPina** 2018-05-22 11:16 UTC
