### ISSUE TITLE
crashes when start

### ISSUE THREAD

**Issue by esteves111** [SilicaAndPina/psvimgtools-frontend#74] opened 2018-03-20 15:41 UTC
Every time i run the "psvimgtools-frontend", it starts but after 2 sec it crashes, i dont know if it is an error or not because its to fast to read. so can someone pls tell me what to do ?

**Comment by esteves111** [comment] 2018-03-20 16:32
ok i already solve this problem but now another problem appeard i cant select a cackup because it says that i dont have none 
so what should i do now?

**Comment by SilicaAndPina** [comment] 2018-03-22 04:53
i need stdout / console

**Comment by tarcisioneto** [comment] 2018-03-23 20:48
with me happened the same, when it starts, it just closes after 2 or 3 seconds. i will put the link of the image that i printed. [https://ibb.co/cR0qaS](url)

**Comment by tarcisioneto** [comment] 2018-03-23 20:50
with me happened the same, when it starts, it just closes after 2 or 3 seconds, this is the link of the image that i printed https://ibb.co/cR0qaS

**Comment by SilicaAndPina** [comment] 2018-03-23 22:33
AID \u what?
also account name is blank? 
wtf

**Comment by tarcisioneto** [comment] 2018-03-23 22:34
I just erased it on photoshop before post.

**Comment by SilicaAndPina** [comment] 2018-03-23 23:33
Yea caz i totally cant see it on the "downloading key from:"

**Comment by tarcisioneto** [comment] 2018-03-23 23:42
Should I post it with no erased parts?

**Comment by SilicaAndPina** [comment] 2018-03-24 01:06
now account name isnt blank, xD

so what exactly is the issue then?

**Comment by tarcisioneto** [comment] 2018-03-24 01:08
It just close after 2 or 3 seconds

**Comment by SilicaAndPina** [comment] 2018-03-24 01:10
can you run it in cmd so i can see the error?

**Comment by tarcisioneto** [comment] 2018-03-24 01:11
Ok i will do it tomorrow morning, I am not in home right now ok?

**Comment by SilicaAndPina** [comment] 2018-03-24 01:14
ok.

**Comment by tarcisioneto** [comment] 2018-03-24 12:32
ok there is the print https://ibb.co/dofVs7

**Comment by YUNGENGAR** [comment] 2018-04-09 19:49
I have the same problem. I can not find the solution anywhere.

**Comment by YUNGENGAR** [comment] 2018-05-22 11:26
I think it's because windows is corrupt. I need to format to work correctly. The problem comes from some problem of packages or modules of windows (8.1)

**Comment by SilicaAndPina** [comment] 2018-05-22 11:30
OOH ITS CAZ UR USING FUCKING 0.5 >_> 
```
    key = getKey()
    print 'CMA Key: ' + key
    text_file = open(getWorkingDir()+'/keys/' + acc, 'w+')
    text_file.write(key)
    text_file.close()
    text_file = open(getWorkingDir()+'/accounts/' + acc, 'w+')
    text_file.write(aid)
    text_file.close()
```

in v0.5 line #333 is 
`    text_file = open(getWorkingDir()+'/keys/' + acc, 'w+')`
makes alot more sense, unicodeDecodeError huh? mmmmhmm 
ok either your account name had some non-ascii characters which my shit didnt check for or your windows username, 

Im gonna blame this on python2.7.14 
i kinda somewhat know how to fix 'unicodeDecodeError' i think i just have to make sure everything i use is in the same format (ex no combining string() objects with unicode() objects, if u try it will attempt to convert unicode() to string() so if you have any weird characters it will get mad at you)

**Comment by YUNGENGAR** [comment] 2018-05-22 11:32
I'm glad to know that you identified the problem.

**Comment by SilicaAndPina** [comment] 2018-05-22 11:36
yep, heck if i was using "program files" as my install location it would probably not have caused anywhere near as many issues, but i cant because i need to be able to write files to the install location and u cant do that in program files/ as its read only unless its being run as an administrator . . . (this is why some winXP programs require admin to be run under anything above windows vista... because on winXP everything has admin by default so you could just write straight to program files no problem>)

**Comment by SilicaAndPina** [comment] 2018-05-22 11:39
anyway, this is kinda just a duplicate of issue #64 . . .

**Closed by SilicaAndPina** 2018-05-22 11:39 UTC
