### ISSUE TITLE
Keeps crashing on opening

### ISSUE THREAD

**Issue by FoxAzureflame** [SilicaAndPina/psvimgtools-frontend#85] opened 2018-05-16 22:03 UTC
Keeps crashing a few seconds after opening. 

![psvimgtools](https://user-images.githubusercontent.com/39350959/40146410-5d4a5898-5933-11e8-9ce1-981483e0c153.png)

**Comment by acortez03** [comment] 2018-05-17 15:33
I am also having this same issue. The psvimgtools-frontend crashes after a few seconds. I am using a windows x64 bit system. Has anyone found a fix? Thanks in advance!

**Comment by velvetmxo** [comment] 2018-05-17 17:09
Same issue for me as well. If I use an older version it works. the updated version is not working.

**Comment by acortez03** [comment] 2018-05-18 00:30
Which version did you use?

**Comment by velvetmxo** [comment] 2018-05-18 01:19
Apparently I used the latest version you have but wouldn't open on my PC. It worked on my laptop....so i am lost for words....eitherway it works. thanks for the hard work

**Comment by lakersoffseason** [comment] 2018-05-18 04:01
made an account just for this. I've tried to use the past five versions of this all with the same error as OP. Had no problems before today, weird.

**Comment by xordinaj** [comment] 2018-05-18 15:34
ok I had this exact same problem as well even with multiple versions it just simply tried to update or broke, and i have found is that adding "noKeyUpdate" to the shortcut fixes the problem.  Hope this helps some of you!
![image](https://user-images.githubusercontent.com/39412923/40243780-f6bf8c26-5a75-11e8-959b-a4bc699a58f0.png)

**Comment by velvetmxo** [comment] 2018-05-18 15:44
Yup @xordinaj the "noKeyUpdate" fixed it and now i can use it on my machine without going to another PC

**Comment by EmuAGR** [comment] 2018-05-19 01:30
That isn't a suitable fix. It disables PFS descryption, rendering the extracted backup almost useless.

**Comment by ironkamakaze** [comment] 2018-05-19 01:51
I'm a total newbie with all of this and just starting out with my first vita mod so this is super frustrating and I have no clue what to do to fix this issue. Is there any other program I can use ?

**Comment by EmuAGR** [comment] 2018-05-19 05:46
I've been reviewing the code, The .csv to .tsv migration was commited, but not released. And NoPayStation removed the .csv files finally. That's why the content of temp.csv is just a 404 error and it can't be parsed.

**Comment by MisereMortem** [comment] 2018-05-20 03:46
My friend is a programmer, and he confirmed what EmuAGR said. So it probably needs to come to author's attention.

**Comment by SilicaAndPina** [comment] 2018-05-21 22:49
Should be fixed in v0.6.1 as he said i allready fixed it just hadnt released this version yet because i wanted to do some other stuff soo i just released it as a pre-release

**Closed** 2018-06-17 17:35 UTC
Labels: bug
